# Generated by Django 4.0.5 on 2022-07-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravaperfumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='tamanho',
            field=models.CharField(choices=[('A', '25ml'), ('B', '30ml'), ('C', '50ml'), ('D', '65ml'), ('E', '75ml'), ('F', '80ml'), ('G', '90ml'), ('H', '100ml'), ('I', '118ml'), ('J', '125ml'), ('K', '150ml'), ('L', '200ml')], default='H', max_length=1),
        ),
    ]
