# Generated by Django 4.0.5 on 2022-07-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravaperfumes', '0002_perfume_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('U', 'Unissex')], default='M', max_length=1),
        ),
    ]
