# Generated by Django 4.0.5 on 2022-07-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravaperfumes', '0003_perfume_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=5)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravaperfumes.perfume')),
            ],
        ),
    ]
