# Generated by Django 4.0.5 on 2022-07-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravaperfumes', '0004_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='tamanho',
            field=models.TextField(choices=[('25ml', '25ml'), ('30ml', '30ml'), ('50ml', '50ml'), ('65ml', '65ml'), ('75ml', '75ml'), ('80ml', '80ml'), ('90ml', '90ml'), ('100ml', '100ml'), ('118ml', '118ml'), ('125ml', '125ml'), ('150ml', '150ml'), ('200ml', '200ml')], default='100ml', max_length=5),
        ),
    ]
