# Generated by Django 4.0.5 on 2022-07-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravaperfumes', '0006_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfume',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
