# Generated by Django 4.0.5 on 2022-07-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravaperfumes', '0008_perfume_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravaperfumes.cliente')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravaperfumes.perfume')),
            ],
        ),
    ]
