# Generated by Django 4.0.5 on 2022-07-24 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gravaperfumes', '0009_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gravaperfumes.perfume'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gravaperfumes.fabricante'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gravaperfumes.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gravaperfumes.perfume'),
        ),
    ]
