# Generated by Django 4.0.5 on 2022-07-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravaperfumes', '0011_alter_venda_data_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='preco_custo',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='preco_venda',
        ),
    ]
