# Generated by Django 4.0.5 on 2022-07-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravaperfumes', '0012_remove_perfume_preco_custo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=20220728, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=20220101, max_digits=10),
            preserve_default=False,
        ),
    ]
